### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by alexandru-bagi** [speed-up-website/freessl.tech-auto#2]
`Error performing query ' CREATE TABLE IF NOT EXISTS `users` ( `id` int(11) NOT NULL, `full_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL, `email` varchar(255) COLLATE utf8_unicode_ci NOT NULL, `password` varchar(255) COLLATE utf8_unicode_ci NOT NULL, `date_created` datetime DEFAULT CURRENT_TIMESTAMP, `pwd_reset_token` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL, `pwd_reset_token_creation_date` datetime DEFAULT NULL ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci; ': Invalid default value for 'date_created'`

I get the following error after completing the install.php form. What should I do?

**Comment by alexandru-bagi** [comment]
Quick fix - 
Edited the /FreeSSLAuto/src/Admin/db.sql file
Changed line 31 - datetime is set to default NULL.

I believe it might be related to MySQL version. The one that the server is using is 5.5.62-cll.

**Comment by speed-up-website** [comment]
Thanks for the update. It is strange that default CURRENT_TIMESTAMP is throwing error.
