### ISSUE TITLE
Cpanel Login Problem - ERROR Cert Issue

### ISSUE THREAD

**Issue by ricardo-jahnke** [speed-up-website/freessl.tech-auto#4]
Hello, I've got a problem when put my permissions to access hostinger cpanel trough your application
even though I write the cpanel address it has been rewritten with:2083 and I got this message below when I try to issue the certificate:
2020-01-05 02:43:24 [info] Oops! We can't connect to your cPanel. Please recheck the cPanel settings and provide correct credentials.

here is the address I wrote:
Your cPanel host/login URL. * => https://cpanel.hostinger.com.br:2083
what can I do to fix it?

Regards

**Comment by speed-up-website** [comment]
@ricardo-jahnke As per my knowledge, cPanel's default port (over https) is 2083 and there is no way to change it. Though Hostinger included the word çpanel in the URL, but most probably it's not cPanel. There feature list tells that it's their own solution. I haven't seen the word çPanel' in their feature list. 
For clarification, I asked them "Do you offer cPanel shared hosting?" In the reply they sent me an email that is another website owned by them, but not www.hostinger.com .

**Comment by ricardo-jahnke** [comment]
Thanks for your help, I have asked them about this issue. I use the shared hosting and I can access cpanel but it is not a regular way to, it's provided by hostinger.  I will research for another option. Regards!
