### ISSUE TITLE
Generate SSL Certificate files

### ISSUE THREAD

**Issue by sobujbd** [speed-up-website/freessl.tech-auto#7]
### Can we generate SSL certificate files through this ?

**Comment by speed-up-website** [comment]
@sobujbd Sure.

**Comment by sobujbd** [comment]
Is there any instructions to do generate SSL certificate files?

**Comment by speed-up-website** [comment]
Please check these videos. One for this client. Another for the WordPress version (plugin) of this.
https://www.youtube.com/watch?v=tYIOHsuY-HE

https://www.youtube.com/watch?v=WqCk9dVLoPw
